# Generated by Django 4.0.4 on 2022-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=200)),
                ('tags', models.CharField(choices=[('work', 'WORK'), ('recipes', 'RECIPES'), ('sports', 'SPORTS')], max_length=50)),
            ],
        ),
    ]
